openapi: 3.0.3
info:
  title: JobTracker API
  version: 1.0.0
paths:
  /api/auth/login/:
    post:
      operationId: api_auth_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/auth/register/:
    post:
      operationId: api_auth_register_create
      description: Registra un usuario y retorna id, username y email.
      summary: Registro de usuario
      tags:
      - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterSuccessResponse'
          description: ''
        '400':
          description: Error de validación
        '429':
          description: Demasiadas solicitudes
  /api/auth/token/refresh/:
    post:
      operationId: api_auth_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/jobs/:
    get:
      operationId: api_jobs_list
      parameters:
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobApplicationList'
          description: ''
    post:
      operationId: api_jobs_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobApplicationList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/JobApplicationList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/JobApplicationList'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplicationList'
          description: ''
  /api/jobs/{id}/:
    get:
      operationId: api_jobs_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplicationDetail'
          description: ''
    put:
      operationId: api_jobs_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobApplicationList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/JobApplicationList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/JobApplicationList'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplicationList'
          description: ''
    patch:
      operationId: api_jobs_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedJobApplicationList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedJobApplicationList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedJobApplicationList'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplicationList'
          description: ''
    delete:
      operationId: api_jobs_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/jobs/{id}/notes/:
    get:
      operationId: api_jobs_notes_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplicationList'
          description: ''
    post:
      operationId: api_jobs_notes_create
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobApplicationList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/JobApplicationList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/JobApplicationList'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplicationList'
          description: ''
  /api/jobs/{id}/notes/{note_id}/:
    delete:
      operationId: api_jobs_notes_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      - in: path
        name: note_id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/jobs/{id}/predict/:
    get:
      operationId: api_jobs_predict_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplicationList'
          description: ''
  /api/jobs/export/csv/:
    get:
      operationId: api_jobs_export_csv_retrieve
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplicationList'
          description: ''
  /api/jobs/stats/:
    get:
      operationId: api_jobs_stats_retrieve
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplicationList'
          description: ''
  /api/jobs/stats/by-industry/:
    get:
      operationId: api_jobs_stats_by_industry_retrieve
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplicationList'
          description: ''
  /api/jobs/stats/timeline/:
    get:
      operationId: api_jobs_stats_timeline_retrieve
      tags:
      - api
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobApplicationList'
          description: ''
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    BlankEnum:
      enum:
      - ''
    JobApplicationDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        company:
          type: string
          maxLength: 200
        position:
          type: string
          maxLength: 200
        industry:
          type: string
          maxLength: 100
        status:
          $ref: '#/components/schemas/ToStatusEnum'
        applied_date:
          type: string
          format: date
        job_url:
          type: string
          format: uri
          maxLength: 200
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        notes:
          type: array
          items:
            $ref: '#/components/schemas/Note'
          readOnly: true
        history:
          type: array
          items:
            $ref: '#/components/schemas/StatusHistory'
          readOnly: true
      required:
      - applied_date
      - company
      - created_at
      - history
      - id
      - notes
      - position
      - status
      - updated_at
    JobApplicationList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        company:
          type: string
          maxLength: 200
        position:
          type: string
          maxLength: 200
        industry:
          type: string
          maxLength: 100
        status:
          $ref: '#/components/schemas/ToStatusEnum'
        applied_date:
          type: string
          format: date
        job_url:
          type: string
          format: uri
          maxLength: 200
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - applied_date
      - company
      - created_at
      - id
      - position
      - status
      - updated_at
    Note:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        content:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - content
      - created_at
      - id
    NullEnum:
      enum:
      - null
    PatchedJobApplicationList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        company:
          type: string
          maxLength: 200
        position:
          type: string
          maxLength: 200
        industry:
          type: string
          maxLength: 100
        status:
          $ref: '#/components/schemas/ToStatusEnum'
        applied_date:
          type: string
          format: date
        job_url:
          type: string
          format: uri
          maxLength: 200
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    Register:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          title: Nombre de usuario
          description: 'Requerido. 150 carácteres como máximo. Únicamente letras,
            dígitos y @/./+/-/_ '
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Dirección de correo electrónico
          maxLength: 254
        password:
          type: string
          writeOnly: true
        password2:
          type: string
          writeOnly: true
      required:
      - email
      - id
      - password
      - password2
      - username
    RegisterSuccessResponse:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
          format: email
      required:
      - email
      - id
      - username
    StatusHistory:
      type: object
      properties:
        from_status:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/ToStatusEnum'
          - $ref: '#/components/schemas/BlankEnum'
          - $ref: '#/components/schemas/NullEnum'
        to_status:
          $ref: '#/components/schemas/ToStatusEnum'
        changed_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - changed_at
      - to_status
    ToStatusEnum:
      enum:
      - applied
      - interview
      - technical
      - offer
      - rejected
      - discarded
      type: string
      description: |-
        * `applied` - Postulado
        * `interview` - Entrevista RR.HH.
        * `technical` - Prueba técnica
        * `offer` - Oferta recibida
        * `rejected` - Rechazado
        * `discarded` - Descartado
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
